LAUN-12 done
sirussu/open-launcher pull request #11
Opened 2020-10-18 18:06 UTC by MikhailShibaev

Все готово кроме версии.

2020-10-18 20:19 UTC, bondiano commented on src/locales/ru.json
> +    "online": "человек"
тут точно нужна [пьюрализация](https://kazupon.github.io/vue-i18n/guide/pluralization.html)

2020-10-19 05:54 UTC, MikhailShibaev commented on src/locales/ru.json
> +    "online": "человек"
Это я для тайтлов сделал. Стремно же будет если человек поменяет язык, а тайтлы захардкожены.

2020-10-19 14:40 UTC, bondiano requested changes
Нужны тесты на компоненты,сторибука.

2020-10-19 14:51 UTC, bondiano requested changes

2020-10-19 14:51 UTC, bondiano commented on src/store/modules/status_bar/lib.ts
> +export const getSummaryOnline = <T extends { online: number }>(realms: Array<T>): number => {
Тут можно ждать конкретный IRealm

2020-10-20 09:22 UTC, MikhailShibaev commented on src/store/modules/status_bar/lib.ts
> +export const getSummaryOnline = <T extends { online: number }>(realms: Array<T>): number => {
поправил

2020-10-22 07:59 UTC, bondiano commented on src/utils/version.ts
> +import { remote } from 'electron'
давай вынесем это не просто в utils, а `utils/remote`, чтобы `utils` не превращалась в помойку из файлов

2020-10-22 08:00 UTC, bondiano commented on src/views/blocks/StatusBarBlock.vue
> +    setInterval(() => {
в теории мы можем убирать статус бар (например, у меня в степерах не будет его), потому давай на destroy делать clearInterval

2020-10-22 08:01 UTC, bondiano commented on src/views/statusBar/StatusBar.vue
> +      {{ realm.name.split(' -')[0] }}
вынеси в `coumputed` `realms.map`, и там сразу имя в нужном виде замапь

2020-10-22 08:02 UTC, bondiano commented on src/views/statusBar/StatusBar.vue
> +      <span v-if="realm.isOnline">&#128994;</span>
вставь прям символ https://unicode-table.com/ru/1F7E2/

2020-10-22 08:03 UTC, bondiano commented on src/views/statusBar/StatusBar.vue
> +      <span v-else>&#128308;</span>
тоже самое https://unicode-table.com/ru/1F534/

2020-10-22 08:03 UTC, bondiano commented on src/views/statusBar/StatusBar.vue
> +      <span v-if="realm.isOnline">&#128994;</span>
вообще, может свгшки притащить или покрасить иконку? нежели такие символы пихать? на некоторых старых ОС могут не поддерживаться

2020-10-22 08:07 UTC, bondiano commented on tests/unit/views/statusBar.spec.ts
> +  test('correct plural ru locale', () => {
внутри `describe` используй `it`, напиши побольше стабов, и пройдись по ним с помощью `it.each`

2020-10-22 10:34 UTC, closed without merging

2020-10-22 13:54 UTC, MikhailShibaev commented on src/utils/version.ts
> +import { remote } from 'electron'
поправил

2020-10-22 13:57 UTC, MikhailShibaev commented on src/views/blocks/StatusBarBlock.vue
> +    setInterval(() => {
done

2020-10-22 14:01 UTC, MikhailShibaev commented on tests/unit/views/statusBar.spec.ts
> +  test('correct plural ru locale', () => {
`it` от `test` же ничем не отличается насколько я знаю, в чем смысл?

2020-10-22 14:12 UTC, MikhailShibaev commented on src/views/statusBar/StatusBar.vue
> +      {{ realm.name.split(' -')[0] }}
done

2020-10-22 14:16 UTC, MikhailShibaev commented on src/views/statusBar/StatusBar.vue
> +      <span v-if="realm.isOnline">&#128994;</span>
это тот же символ ток html код

2020-10-22 14:16 UTC, MikhailShibaev commented on src/views/statusBar/StatusBar.vue
> +      <span v-else>&#128308;</span>
это тот же символ ток html код