[LAUN-14]Done
sirussu/open-launcher pull request #13
Opened 2020-10-20 15:18 UTC by MikhailShibaev

Добавлена периодическая валидация аккаунтов со стопом на 24 часа

2020-10-20 16:45 UTC, bondiano requested changes

2020-10-20 16:45 UTC, bondiano commented on src/store/modules/accounts/adapters.ts
> +      password: authResponse.password
а нам точно нужно пароль сохранять? У нас вроде токен есть

2020-10-20 16:45 UTC, bondiano commented on src/config.ts
> +export const PENDING_TIME_MS = 86400000 // 24 hours
принято такое вычислять явно, так оч сложно понять, ток коммент что-то значит

2020-10-20 16:45 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    lastValidateAccountsTimestamp: 0
`lastValidationTimestamp`

2020-10-20 16:45 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    const currentTime = Date.now()
чувак переедет на +10 часов куда-нибудь (в другой часовой пояс) и тут что-то может произойти

2020-10-20 16:45 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +          await dispatch('removeAccount', account.id)
думаешь стоит прям `removeAccount` делать?

2020-10-20 16:47 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +          await dispatch('removeAccount', account.id)
по старому так делалось

2020-10-20 16:48 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +    const currentTime = Date.now()
`Date.now()` возвращает же по текущему часовому поясу

2020-10-20 16:48 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +    lastValidateAccountsTimestamp: 0
поправил

2020-10-20 16:50 UTC, MikhailShibaev commented on src/store/modules/accounts/adapters.ts
> +      password: authResponse.password
Его неоткуда больше взять. Мы же за кулисами запросы кидаем, а без пароля мы не сможем выполнить запрос.

2020-10-20 16:50 UTC, MikhailShibaev commented on src/store/modules/accounts/adapters.ts
> +      password: authResponse.password
А так идея так себе, солидарен

2020-10-20 16:51 UTC, MikhailShibaev commented on src/config.ts
> +export const PENDING_TIME_MS = 86400000 // 24 hours
Ну я поэтому его и оставил. Ща переделаю

2020-10-20 17:02 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +          await dispatch('removeAccount', account.id)
Но вообще можно какой-нибудь флаг завести и по нему в UI делать акк не доступным для выбора

2020-10-20 17:07 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    const currentTime = Date.now()
а до этого сохранили по другому

2020-10-20 17:07 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +          await dispatch('removeAccount', account.id)
думаю, да, оставлять флаг лучше

2020-10-21 06:43 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +          await dispatch('removeAccount', account.id)
ок

2020-10-22 10:11 UTC, MikhailShibaev commented
Засквошил лишние коммиты из мастера

2020-10-23 18:56 UTC, MikhailShibaev commented
Глянь пока, остались только даты.

2020-10-27 12:35 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +    const currentTime = Date.now()
сделал

2020-10-29 12:33 UTC, bondiano commented on src/config.ts
> +export const DELAY_TIME_MS = 24 * 60 * 60 * 1000 // 24 hours
в новом master'е есть `constants`, давай туда

2020-10-29 12:34 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +        await axios.post('https://api.sirus.su/oauth/token', accountDataToRequestParams)
давай весь процесс валидации делать параллельно, сейчас каждый аккаунт поочередно проверяется

2020-10-29 17:04 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +        await axios.post('https://api.sirus.su/oauth/token', accountDataToRequestParams)
сделал

2020-10-29 17:12 UTC, MikhailShibaev commented on src/config.ts
> +export const DELAY_TIME_MS = 24 * 60 * 60 * 1000 // 24 hours
перенес

2020-10-29 20:38 UTC, bondiano commented on src/constants.ts
> +export const DELAY_TIME_MS = 24 * 60 * 60 * 1000
давай по аналогии. 
```suggestion
export const VERIFY_ACCOUNTS_TIMEOUT = 24 * 60 * 60 * 1000
```

2020-10-30 06:41 UTC, MikhailShibaev commented on src/constants.ts
> +export const DELAY_TIME_MS = 24 * 60 * 60 * 1000
поправил

2020-10-30 11:57 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +  async beforeValidateAccountsCheck({ dispatch, state }) {
это же просто `validateAccounts`, не?

2020-10-30 11:57 UTC, bondiano commented on src/store/modules/accounts/lib.ts
> +  if (stateTimezone && currentTimezone !== stateTimezone) {
просто `return stateTimezone && currentTimezone !== stateTimezone`

2020-10-30 11:57 UTC, bondiano commented on src/store/modules/accounts/lib.ts
> +  if (currentTimestamp > stateTimestamp) {
просто `return currentTimestamp > stateTimestamp`

2020-10-30 11:58 UTC, bondiano commented on src/store/modules/accounts/lib.ts
> +export const getDate = () => new Date()
а это зачем?

2020-10-30 11:59 UTC, bondiano commented on src/views/App.vue
> +    await this.$store.dispatch('accounts/validationTimezoneCheck', {
зачем два экщена поочереди?

2020-10-30 12:11 UTC, MikhailShibaev commented on src/store/modules/accounts/lib.ts
> +  if (stateTimezone && currentTimezone !== stateTimezone) {
я для простоты оставил так, чтоб нагляднее было

2020-10-30 12:11 UTC, MikhailShibaev commented on src/store/modules/accounts/lib.ts
> +export const getDate = () => new Date()
они обе не нужны?

2020-10-30 12:56 UTC, MikhailShibaev commented on src/store/modules/accounts/lib.ts
> +export const getDate = () => new Date()
убрал

2020-10-30 12:56 UTC, MikhailShibaev commented on src/store/modules/accounts/lib.ts
> +  if (currentTimestamp > stateTimestamp) {
поправил

2020-10-30 12:56 UTC, MikhailShibaev commented on src/store/modules/accounts/lib.ts
> +  if (stateTimezone && currentTimezone !== stateTimezone) {
поправил

2020-10-30 12:57 UTC, MikhailShibaev commented on src/views/App.vue
> +    await this.$store.dispatch('accounts/validationTimezoneCheck', {
вложил один в другой

2020-10-30 12:57 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +  async beforeValidateAccountsCheck({ dispatch, state }) {
поправил

2020-11-02 07:08 UTC, merged