Laun 39 done
sirussu/open-launcher pull request #16
Opened 2020-11-03 16:59 UTC by MikhailShibaev

## 39 таска 
* Добавлены прогресс бары в модальные окна
* Добавлены оповещения об ошибках

2020-11-05 07:26 UTC, bondiano requested changes

2020-11-05 07:26 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +      <!--<template #activator="{ on }">
почему закоменченно?

2020-11-05 07:26 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +      required: true,
required + default ?

2020-11-05 07:26 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +      return this.getStatus === 'PENDING'
бери из enum'а

2020-11-05 07:26 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +      await this.modalToggle(false)
await?

2020-11-05 17:12 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +      <!--<template #activator="{ on }">
Удалю

2020-11-05 17:13 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +      required: true,
Уберу)

2020-11-05 17:13 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +      return this.getStatus === 'PENDING'
Ок

2020-11-05 17:13 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +      await this.modalToggle(false)
Сам хз зачем его там воткнул. Посмотрю

2020-11-05 18:49 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    if (state.accounts.data.byId[account.id] && state.accounts.data.byId[account.id].tokenIsExpired) {
на это нужен тест

2020-11-05 18:50 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +    modalToggle(toggle: boolean) {
Все методы - глаголы

2020-11-05 18:50 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
>      async tfaWasEntered(tfaToken: string) {
методы - глаголы

2020-11-05 18:51 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
>        this.switchOffTfa()
switchOffTfa - странное название

2020-11-05 18:51 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
почему тут? что это? состояние?

2020-11-05 18:51 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
звучит как функция

2020-11-05 18:52 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +      this.tfaModalToggle = false
странное название

2020-11-05 18:52 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +      type: Object,
`hasTfa` - объект?

2020-11-05 18:52 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +    showProgressBar: {
звучит как функция

2020-11-05 18:52 UTC, bondiano commented on src/views/accounts/TfaModal.vue
>    name: 'TfaModal',
зачем тут `name`?

2020-11-05 18:52 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +      this.showModalComp = true
звучит как функция

2020-11-05 18:53 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +    showModalComp: {
что такое `Comp`?

2020-11-05 18:53 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    if (account.tfaToken) {
нужен тест на этот кейс

2020-11-05 18:53 UTC, bondiano commented on src/locales/ru.json
> +    "send_auth_request": "Не можем авторизовать вас. Попробуйте позже или обратитесь в поддержку",
как им в поддержку обращаться?

2020-11-06 08:54 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +      type: Object,
переименовал в `tfa`

2020-11-06 08:55 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
переименовал в `modal`

2020-11-06 08:55 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
>        this.switchOffTfa()
хз как по другому назвать. именовал по смыслу)

2020-11-06 08:58 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
>      async tfaWasEntered(tfaToken: string) {
переименовал в `switchModalToggle`

2020-11-06 08:58 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +    modalToggle(toggle: boolean) {
переименовал в `switchModalToggle`

2020-11-06 08:59 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +      await this.modalToggle(false)
убрал

2020-11-06 09:01 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
> звучит как функция

переименовал в `modal`

2020-11-06 09:02 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
> почему тут? что это? состояние?

Источник истины - `AccountsBlock.vue`, потому это там. Да это состояние дочернего компонента.

2020-11-06 09:04 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +      this.tfaModalToggle = false
`tfaModalToggle` - именовал по смыслу)) это ж переключатель модального окна 2фа

2020-11-06 09:06 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +    showProgressBar: {
переименовал в `progressBar`

2020-11-06 09:06 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +      this.showModalComp = true
переименовал в `modalToggle`

2020-11-06 09:07 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +    showModalComp: {
computed, пока я там все переделывал у меня была `showModal` переменная в стейте

2020-11-06 09:08 UTC, MikhailShibaev commented on src/locales/ru.json
> +    "send_auth_request": "Не можем авторизовать вас. Попробуйте позже или обратитесь в поддержку",
это взято из таски, видимо потом будет понятно как обратится в поддержку)

2020-11-06 09:13 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
>        this.switchOffTfa()
переименовал в `closeTfaModal`

2020-11-06 09:14 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
>    name: 'TfaModal',
убрал, шторм по дефолту создает компоненты с этим полем

2020-11-06 10:50 UTC, MikhailShibaev commented on src/store/modules/accounts/index.ts
> +    if (account.tfaToken) {
сделал

2020-11-06 16:23 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +      this.showModalComp = true
это же флаг например `isModalOpened`

2020-11-06 19:49 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +    const showModal = false
так состояние в хуках - через ref

2020-11-06 19:49 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +      this.tfaModalToggle = false
это boolaen

2020-11-07 08:39 UTC, bondiano commented
![image](https://user-images.githubusercontent.com/323479/98436545-444a7380-20ed-11eb-9144-ca9a3a6b9934.png)
1.  Большое расстояние до звездочки
2. Не закрывать модалку при ошибке
3. Добавить текст Забыл пароль с ссылкой на https://sirus.su/user/password/reset#/. 
4. На пустые поля не надо реагировать вообще
5. Вынести 2FA модалку отдельно (чтобы можно было любую модалку переиспользовать в разных местах)

2020-11-07 08:45 UTC, bondiano commented on src/store/modules/accounts/index.ts
> +    if (state.accounts.data.byId[account.id] && state.accounts.data.byId[account.id].tokenIsExpired) {
и кажется, это стоит вынести в отдельный экшен

2020-11-07 08:45 UTC, bondiano commented on src/store/modules/accounts/index.ts
>      if (state.accounts.data.allIds.includes(account.id)) {
`isAccountExists`

2020-11-07 12:14 UTC, MikhailShibaev commented
> кажется тут бага с удалением 0левого аккаунта, когда у него есть defaultID
Поправил

> Кажется у тебя приттер не срабатывает
Поправил

2020-11-08 08:29 UTC, bondiano commented on src/views/accounts/AccountsModal.vue
> +      const fieldsAreFill =
снова неверное именование для boolean переменных

2020-11-08 08:30 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +    tfaModalToggle: {
снова неверное именование для boolean переменых

2020-11-08 08:31 UTC, bondiano commented on src/views/accounts/TfaModal.vue
> +      type: Object,
опиши все пропсы typescript'ом https://github.com/sirussu/open-launcher/blob/36afdc8cee65d80d48541b8f31a7dc1bae88d195/src/views/feeds/FeedCard.vue#L23

2020-11-08 08:33 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
> +        this.switchModalToggle(false)
лучше заведи методы `hideModal` и `showModal`, там уже с аргументом дергай `switchModalToggle`

2020-11-08 08:34 UTC, bondiano commented on src/views/blocks/AccountsBlock.vue
>      async tfaWasEntered(tfaToken: string) {
`tfaWasEntered` так и осталось

2020-11-08 08:35 UTC, bondiano commented on tests/unit/store/modules/accounts.spec.ts
> +    normalizedAccountStub.byId.tokenIsExpired = false // TODO: don't know why this set as 'true'. In stub this field setted as 'false'!
это дичь, надо разобраться и похоже у тебя где-то по ходу тестов изменяется объект стаба.

2020-11-08 08:35 UTC, bondiano requested changes
Поправь замечания

2020-11-08 08:57 UTC, MikhailShibaev commented on tests/unit/store/modules/accounts.spec.ts
> +    normalizedAccountStub.byId.tokenIsExpired = false // TODO: don't know why this set as 'true'. In stub this field setted as 'false'!
Я искал - не нашел. В пн гляну на свежую голову.

2020-11-09 09:36 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +      type: Object,
сделал

2020-11-09 09:36 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +      this.showModalComp = true
переименовал

2020-11-09 09:37 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +      this.tfaModalToggle = false
переименовал

2020-11-09 09:40 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
>      async tfaWasEntered(tfaToken: string) {
`sendRequestWithTfa`

2020-11-09 09:45 UTC, MikhailShibaev commented on src/views/accounts/AccountsModal.vue
> +      const fieldsAreFill =
`hasFieldsFilled`

2020-11-09 09:45 UTC, MikhailShibaev commented on src/views/accounts/TfaModal.vue
> +    tfaModalToggle: {
`isTfaModalOpened`

2020-11-09 11:23 UTC, MikhailShibaev commented on src/views/blocks/AccountsBlock.vue
> +        this.switchModalToggle(false)
сделал

2020-11-10 11:24 UTC, merged